Add SWEP Shaped Charge
CFC-Servers/cfc_pvp_weapons pull request #1
Opened 2020-11-02 05:02 UTC by wrefgtzweve

2020-11-03 21:30 UTC, brandonsturgeon requested changes
Lookin' good! Can't wait to try it out.

All of my comments were nit-picky styling comments or general suggestions.

I see a mix of tabs and spaces, and the spacing is generally kind of "off", so be sure to do a run-thru and make sure everything is using spaces.

Also, I noticed some styling violations. Be sure you skim through the style guidelines and update accordingly. (For example, I saw some tables without spaces inside, operators without spaces around them, etc.)

I think the players will love it!

2020-11-03 21:30 UTC, brandonsturgeon commented on lua/entities/cfc_shaped_charge/cl_init.lua
> +    explodeTime = CurTime() + GetConVar( "cfc_shaped_charge_timer" ):GetInt()
We can place it directly on the entity here
```suggestion
    self.explodeTime = CurTime() + GetConVar( "cfc_shaped_charge_timer" ):GetInt()
```

2020-11-03 21:30 UTC, brandonsturgeon commented on lua/entities/cfc_shaped_charge/cl_init.lua
> +    print(timeLeft..""..m.." "..s)
```suggestion
```

2020-11-03 21:30 UTC, brandonsturgeon commented on lua/entities/cfc_shaped_charge/cl_init.lua
> +    local m, s = self:FormatTime( timeLeft )
This can just be
```suggestion
    local minutes, seconds = self:FormatTime( timeLeft )
```

2020-11-03 21:30 UTC, brandonsturgeon commented on lua/entities/cfc_shaped_charge/init.lua
> +    blastRange  = GetConVar( "cfc_shaped_charge_blastrange" ):GetInt()
These could all be on `self.` instead of a local var in this file

2020-11-03 21:30 UTC, brandonsturgeon commented on lua/entities/cfc_shaped_charge/init.lua
> +    bombLight:Spawn()
Might be nice to move this to its own function
```
self:CreateLight()
```

2020-11-03 21:30 UTC, brandonsturgeon commented on lua/entities/cfc_shaped_charge/init.lua
> +            util.Effect( "Sparks", effectdata )
This could also go into its own function
```lua
self:CreateSparkEffect()
```

2020-11-03 21:30 UTC, brandonsturgeon commented on lua/entities/cfc_shaped_charge/init.lua
> +    end
Usually we'd space this out like so:
```suggestion
    local owner = self.Owner

    owner.plantedCharges = owner.plantedCharges or 0
    owner.plantedCharges = owner.plantedCharges - 1

    if owner.plantedCharges <= 0 then
        owner.plantedCharges = nil
    end
```

2020-11-03 21:30 UTC, brandonsturgeon commented on lua/entities/cfc_shaped_charge/init.lua
> +    util.Effect( "Explosion", effectdata )
Same deal, could split this guy out:
```lua
self:CreateExplosionEffect()
```

2020-11-03 21:30 UTC, brandonsturgeon commented on lua/entities/cfc_shaped_charge/init.lua
> +        if IsValid( prop ) and prop:MapCreationID() == -1 then
This could be its own function too, which would allow us to easily modify what it's allowed to destroy in the future:

```lua
if self:CanDestroyProp( prop ) then
```

2020-11-03 21:30 UTC, brandonsturgeon commented on lua/entities/cfc_shaped_charge/init.lua
> +            end
I'd space this out a little more
```suggestion
            local shouldDestroy = hook.Call( "CFC_SWEP_Shaped_Charge", entityToDestroy )

            if shouldDestroy ~= false then 
               prop:Remove()
            end
```

2020-11-03 21:30 UTC, brandonsturgeon commented on lua/entities/cfc_shaped_charge/init.lua
> +function ENT:soundLight()
I think it's standard to use PascalCase for methods on an instance like this
```suggestion
function ENT:SoundLight()
```

Also maybe a better name?
```lua
function ENT:RunCountdownEffects()
```

2020-11-03 21:30 UTC, brandonsturgeon commented on lua/entities/cfc_shaped_charge/init.lua
> +    end)
Some weird spacing in here

```suggestion
    timer.Simple( 0.2, function()
        if not IsValid( self ) then return end

        bombLight:SetKeyValue( "brightness", 0 )
    end )
```

2020-11-03 21:30 UTC, brandonsturgeon commented on lua/entities/cfc_shaped_charge/init.lua
> +            end
Could add a space between the setup and the action
```suggestion
            local shouldDestroy = hook.Call( "CFC_SWEP_Shaped_Charge", entityToDestroy )

            if shouldDestroy ~= false then 
               prop:Remove()
            end
```

2020-11-03 21:30 UTC, brandonsturgeon commented on lua/weapons/cfc_weapon_shaped_charge/shared.lua
> +SWEP.Secondary.Automatic    = false // Automatic/Semi Auto
Some Gmod comments here. `--` is preferred

2020-11-03 21:30 UTC, brandonsturgeon commented on lua/weapons/cfc_weapon_shaped_charge/shared.lua
> +        end
```suggestion
        local ammo = self.Owner:GetAmmoCount( "shapedCharge" )

        if ammo == 0 then
            self.Owner:StripWeapon( "cfc_weapon_shaped_charge" )
            return
        end
```

2020-11-03 21:30 UTC, brandonsturgeon commented on lua/weapons/cfc_weapon_shaped_charge/shared.lua
> +	viewTrace.endpos = self.Owner:GetShootPos() + 100 * self.Owner:GetAimVector()
Do we want to make this `+100` configurable? Or maybe out in a constant up top?

Having to dig through the code here to change some of the core functionality can be a little cumbersome. Putting things like this in places that are easy to modify will serve yourself (and us!) well in the future.

2020-11-03 21:30 UTC, brandonsturgeon commented on lua/weapons/cfc_weapon_shaped_charge/shared.lua
> +    if trace.HitNonWorld == false or ( self.Owner.plantedCharges or 0 ) >= GetConVar( "cfc_shaped_charge_maxcharges" ):GetInt() then
This is a little complex and could be broken down:

```suggestion
    local hitWorld = trace.HitNonWorld == false
    local maxCharges = GetConVar( "cfc_shaped_charges_maxcharges" ):GetInt()
    local hasMaxCharges = ( self.Owner.plantedCharges or 0 ) >= maxCharges
    
    if hitWorld or hasMaxCharges then
```

2020-11-03 23:05 UTC, wrefgtzweve commented on lua/weapons/cfc_weapon_shaped_charge/shared.lua
> +	viewTrace.endpos = self.Owner:GetShootPos() + 100 * self.Owner:GetAimVector()
That's the distance the player can place the bomb from, i don't think its necessary as a custom var since i don't see any reason you'd want to change it. However i do think that the break trace should be configurable which ill add.

2020-11-11 00:07 UTC, legokidlogan commented on lua/entities/cfc_shaped_charge/init.lua
> +
If someone using this addon wanted something special to happen when the bomb gets shot off (such as doing partial damage to the props via SPD or causing a big explosion that damages nearby players), they'd need a hook to latch onto, so let's give them one via a function.
```suggestion
        
        self:OnDestroyed()
        
```

2020-11-11 00:07 UTC, legokidlogan commented on lua/entities/cfc_shaped_charge/init.lua
> +
```suggestion

function ENT:OnDestroyed()
    local props = ents.FindAlongRay( self:GetPos(), self:GetPos() + self.traceRange * -self:GetUp() )
    local count = #props
    
    --Going in reverse ensures we don't cause any issues when removing from the list, as doing so moves the keys around
    for k, prop in pairs( table.Reverse( props ) ) do
        if not self:CanDestroyProp( prop ) then
            table.remove( props, count - k + 1 )
        end
    end
    
    hook.Run( "CFC_SWEP_ShapedCharge_Destroyed", self, props )
end

```

2020-11-11 05:26 UTC, wrefgtzweve commented on lua/entities/cfc_shaped_charge/init.lua
> +
Currently not needed.

2020-11-17 07:01 UTC, brandonsturgeon requested changes
Style suggestions, code structure looks good 👍

2020-11-17 07:01 UTC, brandonsturgeon commented on lua/weapons/cfc_weapon_shaped_charge/init.lua
> +    if hitWorld or hasMaxCharges or isPlayer or isNPC then
```suggestion
    local isInvalidTarget = hitWorld or hasMaxCharges or isPlayer or isNPC

    if isInvalidTarget then
```

2020-11-17 07:01 UTC, brandonsturgeon commented on lua/weapons/cfc_weapon_shaped_charge/init.lua
> +        FixAngles:RotateAroundAxis(FixAngles:Forward(), FixRotation.z)
Also capitalization
```suggestion
        FixAngles:RotateAroundAxis( FixAngles:Right(), FixRotation.x )
        FixAngles:RotateAroundAxis( FixAngles:Up(), FixRotation.y )
        FixAngles:RotateAroundAxis( FixAngles:Forward(), FixRotation.z )
```

2020-11-17 07:01 UTC, brandonsturgeon commented on lua/weapons/cfc_weapon_shaped_charge/shared.lua
> +SWEP.Author			= "Redox"
Mix of tabs and spaces in this file

2020-11-28 23:22 UTC, brandonsturgeon approved these changes

2020-11-28 23:35 UTC, merged