Get rid of dud parachutes
CFC-Servers/cfc_pvp_weapons pull request #13
Opened 2021-11-05 20:32 UTC by legokidlogan

Fixes the issue where parachutes sometimes fail to function, tracks keys that are held while the chute is being spawned in, and stops chute entities from showing up on the FPP owner indicator.

2021-11-12 20:12 UTC, brandonsturgeon requested changes
Just some performance concerns. As long as the actual change is tested I can sign off on that

2021-11-12 20:12 UTC, brandonsturgeon commented on lua/autorun/server/sv_parachute.lua
>          if IsValid( wep ) then
The users can decide how many of these exist, so I'm kind of concerned about there being a for loop on think.
Maybe a timer could be more appropriate?

Either way, localizing a few things in here would be a good call. `IsValid` is a good one, it's used every execution of every loop.

2021-11-12 20:12 UTC, brandonsturgeon commented on lua/weapons/cfc_weapon_parachute/init.lua
> +    end
Any way to make AllChuteSweps a table? KeyFromValue, RemoveByValue, etc. is a real performance sink - especially because it's triggered by a user action

2021-11-12 20:12 UTC, brandonsturgeon commented on lua/weapons/cfc_weapon_parachute/init.lua
> +        if not IsValid( owner ) or not owner:IsPlayer() then return end
I like to split these into their own lines. I think it helps understand what's expected in the function going forward

2021-11-12 20:12 UTC, brandonsturgeon commented on lua/weapons/cfc_weapon_parachute/init.lua
> +        if moveKey ~= IN_JUMP or owner:GetInfoNum( "cfc_parachute_unfurl_toggle", 0 ) == 0 then
Let's do the unfurl check once before this loop if possible. Again, not loving the performance implications here

2021-11-12 20:23 UTC, legokidlogan commented on lua/autorun/server/sv_parachute.lua
>          if IsValid( wep ) then
It's on think because it works with physics and has to ensure everything's smooth and stable, be able to limit horizontal air speed, etc. `:ApplyChuteForces()` doesn't do anything if the chute is closed, so the amount of actual calculations is limited by the player count. I can definitely localize `IsValid` though.

2021-11-12 20:38 UTC, legokidlogan commented on lua/weapons/cfc_weapon_parachute/init.lua
> +    end
In order to do it without using a `ByValue` function, I'd either need to not have a sequential table or store index values to each parachute SWEP. The former would be inefficient for the `Think` hook which `AllChuteSweps` gets used on, and the latter would be only slightly faster than this method while requiring a good chunk of extra code to update all the other index values.

Besides, the most damage they could do by removing and spawning chutes each tick while keeping a ton spawned in pales in comparison to the lag someone can make by simply piling a bunch of SWEPS all into one corner (especially for gun SWEPs).

2021-11-12 20:43 UTC, legokidlogan commented on lua/weapons/cfc_weapon_parachute/init.lua
> +        if not IsValid( owner ) or not owner:IsPlayer() then return end
It's just a simple `is owner valid and a player` confirmation, I don't feel like splitting it into a second line would change the readability by much.

2021-11-12 20:48 UTC, brandonsturgeon commented on lua/weapons/cfc_weapon_parachute/init.lua
> +        if not IsValid( owner ) or not owner:IsPlayer() then return end
Just a suggestion. I think it does, and adding more expectations later is easier and clearer with no refactoring needed

2021-11-12 20:51 UTC, brandonsturgeon commented on lua/weapons/cfc_weapon_parachute/init.lua
> +    end
It could just be a lookup table. `AllChuteSweps[self] = true`, `AllChuteSweps[self] = nil` and so forth.

Ideally we could get rid of the need to have to loop over these very often. I don't actually see why these need to be kept track of to begin with, actually

2021-11-12 20:55 UTC, legokidlogan commented on lua/weapons/cfc_weapon_parachute/init.lua
> +        if not IsValid( owner ) or not owner:IsPlayer() then return end
Later expectations can be done on a new line, I tend to section off return clauses by what things they're checking and/or by length. This is nice and short, but specifically about validating the player, so it's unlikely that future expectations would cause any hiccups.

2021-11-12 20:59 UTC, legokidlogan commented on lua/weapons/cfc_weapon_parachute/init.lua
> +    end
They need to be tracked for use in the `Think` hook which runs `:ApplyChuteForces()` on all chutes, which is the function which makes them actually slow people's descent.

I'd love to use `SWEP:Think()` but that only runs when the SWEP is actively held, so if someone has a chute open and they switch to a gun, they'd immediately plummet to the ground.

If we used a lookup table, the `Think` hook would have to use `pairs()` and would become a lot less performant.

2021-11-17 04:39 UTC, loganlearner commented on lua/weapons/cfc_weapon_parachute/init.lua
> +    if not IsValid( owner ) or not owner:IsPlayer() then return end
```suggestion
    if not ( IsValid( owner ) or owner:IsPlayer() ) then return end
```
I think this reads a little bit better, reading the logic here was a bit confusing to me.

2021-11-17 04:39 UTC, loganlearner commented on lua/autorun/server/sv_parachute.lua
> +        CFC_Parachute.AllChuteSwepsCount = #allChuteSweps
Correct me if I'm wrong but isn't it better to use `table.count()` here? As I recall using the pound operator if there were ever any gaps in the table the count would be incorrect... This includes NULL entities.

2021-11-17 04:45 UTC, legokidlogan commented on lua/autorun/server/sv_parachute.lua
> +        CFC_Parachute.AllChuteSwepsCount = #allChuteSweps
There's never any gaps in the table, `table.remove()` and inserting to the table's end ensures that. `NULL` entities are still full table entries, it's `nil` that causes entries to disappear.

2021-11-17 04:53 UTC, legokidlogan commented on lua/weapons/cfc_weapon_parachute/init.lua
> +    if not IsValid( owner ) or not owner:IsPlayer() then return end
`not COND or not COND`, etc is the format most often used in CFC code.

Also, the point of doing it this way is to make use of short-circuiting. In the first case, if `owner` is invalid, it instantly skips to the return. In the second case, it'll still try to evaluate `owner:IsPlayer()` which in some cases might yield a nil error, if `owner` is something other than an entity, such as if it was `nil`. It'd use up more time since it checks both values every time, and in some rare cases could result in an error.

2021-11-17 05:00 UTC, wrefgtzweve commented on lua/weapons/cfc_weapon_parachute/init.lua
> +    if not IsValid( owner ) or not owner:IsPlayer() then return end
why not just split the statements up

2021-12-06 22:30 UTC, brandonsturgeon approved these changes

2021-12-06 22:30 UTC, merged