Add slappers
CFC-Servers/cfc_pvp_weapons pull request #49
Opened 2022-11-10 13:56 UTC by wrefgtzweve

2022-11-10 14:05 UTC, wrefgtzweve commented on lua/weapons/cfc_slappers/shared.lua
> +    if ent:Disposition( self:GetOwner() ) ~= 3 then
Damage logic

2022-11-21 01:37 UTC, brandonsturgeon requested changes
idk, take what you want. There are some important changes in here though

2022-11-21 01:37 UTC, brandonsturgeon commented on lua/weapons/cfc_slappers/shared.lua
> +            ent:Fire( "Break" )
```suggestion
            ent:Fire( "Break", "nil", 0, owner, ent )
```

2022-11-21 01:37 UTC, brandonsturgeon commented on lua/weapons/cfc_slappers/shared.lua
> +        ent:Use( self:GetOwner(), self:GetOwner() ) -- Open door
```suggestion
local interactables = {
    func_door = true,
    func_button = true,
    gmod_button = true,
    gmod_wire_button = true,
    func_door_rotating = true,
    prop_door_rotating = true,
}

function SWEP:SlapProp( ent, tr )
    local vec = ( tr.HitPos - tr.StartPos ):GetNormal()
    local emitSound = self.Sounds.HitWorld
    local damage = math.random( 4, 6 )

    if interactables[ent:GetClass()] then
        local owner = self:GetOwner()
        ent:Use( owner, owner ) -- Press button
```

2022-11-21 01:37 UTC, brandonsturgeon commented on lua/weapons/cfc_slappers/shared.lua
> +        end
Do we need to reset the animation too?
```suggestion
        if not IsValid( self ) then return end
        self:SetWeaponHoldType( self.HoldType )
```

2022-11-21 01:37 UTC, brandonsturgeon commented on lua/weapons/cfc_slappers/shared.lua
> +    weapon:SlapAnimation()
On server, this message re-broadcasts the message to all connected clients.
For that reason (and the more obvious reason), this should absolutely be rate limited.

```suggestion
    local ply = net.ReadEntity()
    if not IsValid( ply ) then return end

    local weapon = ply:GetActiveWeapon()
    if not IsValid( weapon ) then return end
    if not weapon.SlapAnimation then return end

    local now = CurTime()
    if weapon.NextSlapAnimation > now then return end
    weapon.NextSlapAnimation = now + self.Primary.Delay

    weapon:SlapAnimation()
```

2022-11-21 01:37 UTC, brandonsturgeon commented on lua/weapons/cfc_slappers/shared.lua
> +    end
```suggestion
    if not SERVER then return end

    -- Use view model slap animation
    self:SendWeaponAnim( ACT_VM_PRIMARYATTACK_2 )

    local punchScale = 1
    local owner = self:GetOwner()
    local shootPos = owner:GetShootPos()

    -- Trace for slap hit
    local tr = util.TraceHull( {
        start = shootPos,
        endpos = shootPos + owner:GetAimVector() * 54,
        mins = self.Mins,
        maxs = self.Maxs,
        filter = owner
    } )

    local ent = tr.Entity

    if IsValid( ent ) or game.GetWorld() == ent then
        if ent:IsPlayer() then
            self:SlapPlayer( ent, tr )
        elseif ent:IsNPC() then
            self:SlapNPC( ent, tr )
        elseif ent:IsWorld() then
            self:SlapWorld( ent, tr )
        else
            self:SlapProp( ent, tr )
        end
    else
        owner:EmitSound( self.Sounds.Miss, 80, math.random( 92, 108 ) )
        punchScale = 0.1
    end

    local side = -4
    if self.ViewModelFlip then
        side = -side
    end

    local oldPunchAng = owner:GetViewPunchAngles()
    local punchAng = oldPunchAng + Angle( -6, side, 0 ) * punchScale
    owner:ViewPunch( punchAng )
```

2022-11-27 22:41 UTC, StrawWagen commented on lua/weapons/cfc_slappers/shared.lua
> +                local angdiff = angles - ( attach.Ang + Angle( 0, 0, -90 ) )
Resolved!

2022-11-27 22:41 UTC, StrawWagen commented on lua/weapons/cfc_slappers/shared.lua
> +    weapon:SlapAnimation()
Applied!

2022-11-28 21:53 UTC, StrawWagen commented on lua/weapons/cfc_slappers/shared.lua
> +    end )
Applied

2022-11-29 19:45 UTC, StrawWagen commented on lua/weapons/cfc_slappers/shared.lua
> +    end
Applied

2022-11-29 20:21 UTC, StrawWagen commented on lua/weapons/cfc_slappers/shared.lua
> +            ent:SetLocalVelocity( vel )
Reworked

2022-11-29 20:26 UTC, StrawWagen commented on lua/weapons/cfc_slappers/shared.lua
> +    self:GetOwner():EmitSound( table.Random( self.Sounds.Slap ), 80, math.random( 92, 108 ) )
Applied

2022-11-29 20:31 UTC, StrawWagen commented on lua/weapons/cfc_slappers/shared.lua
> +end
Applied

2022-11-29 20:32 UTC, StrawWagen commented on lua/weapons/cfc_slappers/shared.lua
> +    end
Applied

2022-11-29 20:32 UTC, StrawWagen commented on lua/weapons/cfc_slappers/shared.lua
> +        ent:EmitSound( table.Random( self.Sounds.Hurt ), 50, math.random( 95, 105 ) )
Applied!

2022-11-29 20:33 UTC, StrawWagen commented on lua/weapons/cfc_slappers/shared.lua
> +    local punchAng = oldPunchAng + Angle( -3, 2, 0 )
Applied

2022-11-29 20:33 UTC, StrawWagen commented on lua/weapons/cfc_slappers/shared.lua
> +    ply:EmitSound( table.Random( self.Sounds.Hurt ), 50, math.random( 92, 108 ) )
Applied!

2022-12-19 10:54 UTC, wrefgtzweve commented on lua/weapons/cfc_super_slappers/shared.lua
> +SWEP.Bonk.Enabled = true
there's no bonk subtable so this is just going to error

2022-12-23 02:31 UTC, StrawWagen commented on lua/weapons/cfc_super_slappers/shared.lua
> +SWEP.Bonk.Enabled = true
Shit, you're right.

2022-12-23 02:59 UTC, legokidlogan commented on lua/weapons/cfc_super_slappers/shared.lua
> +SWEP.Bonk.Enabled = true
The bonk stuff is also not merged yet and is part of the B/K stubber repo. It'll be better if we stubbed slappers (just like with any other SWEP) to add the impact damage, rather than make this repo *inherently* need the stubber as a dependency.

2022-12-24 15:25 UTC, wrefgtzweve commented
We should get this playtested and merged, its getting too old for no reason.

2023-01-22 19:13 UTC, wrefgtzweve commented
status on this pr?

2023-01-23 08:32 UTC, brandonsturgeon approved these changes

2023-01-29 21:23 UTC, merged