CFC-125 Rework Parachutes
CFC-Servers/cfc_pvp_weapons pull request #57
Opened 2023-08-25 22:37 UTC by legokidlogan

- Brings back cfc_parachute and related files.
- Partial code cleanup to improve maintenance and better fit current style.
- Adds key combos to quickly equip/open/close parachutes without ever having to touch the SWEP.
  - These are configurable, with the default settings making it near identical to how z-parachutes are operated.
- Rebalanced server settings to reduce horizontal mobility and make weapon instability less punishing.

TODO:
- [ ] Make a PR in [cfc_pvp](https://github.com/CFC-Servers/cfc_pvp) to return false in the `CFC_Parachute_IsSpaceEquipEnabled` hook if a player is in build mode and does not currently have a parachute SWEP equipped.

2024-01-18 02:22 UTC, brandonsturgeon requested changes
Overall looking good. My review focuses primarily on performance, technical hangups, and code simplification.

I think people really want something simple to use, and we want something simple to maintain.

To that end, I've questioned a few systems:
- LFS Integration
- Possibly overly-strict (and wordy) "CanUseTheParachute" checks that span multiple files
- Lurch mechanic


Notes:
- I'm a little concerned about the ground detection. Right now it seems like the "ground" can be any trace-able entity below the player. I wonder if this would cause some wonky behavior if they glide over a floating/flying contraption.
- It would likely be much more efficient to maintain a table of players' parachutes on SERVER rather than storing them on the player. You could do both, but all of the internal code could reference the table much more efficiently than `__index`ing the player.
- Lots of opportunities to localize frequently called methods
- It seems expensive and kind of unnecessary to have the "SpaceEquipReady" logic. Doing a movetype/velocity/isonground/alive check on keypress seems simpler and not performance heavy.
- You can remove some of the model format files:
  - `.dx80.vtx`
  - `.sw.vtx`

2024-01-18 02:22 UTC, brandonsturgeon commented on lua/cfc_pvp_weapons/shared/sh_parachute_convars.lua
> +CreateConVar( "cfc_parachute_quick_close_advanced_sv", 0, { FCVAR_ARCHIVE, FCVAR_REPLICATED }, "Makes quick-close require walk and crouch to be pressed together. Defines the default value for players
Do all of these need to be shared/replicated?

Keep in mind that Convar callbacks [**don't** work clientside for Replicated convars](https://github.com/Facepunch/garrysmod-issues/issues/3740)

2024-01-18 02:22 UTC, brandonsturgeon commented on lua/cfc_pvp_weapons/shared/sh_parachute_convars.lua
> +CreateConVar( "cfc_parachute_quick_close_advanced_sv", 0, { FCVAR_ARCHIVE, FCVAR_REPLICATED }, "Makes quick-close require walk and crouch to be pressed together. Defines the default value for players
I think you should make these a table on the CFC_Parachutes table so you can get them by a "config name" - getting them by name later means it's slightly more annoying to change the convar names.

2024-01-18 02:22 UTC, brandonsturgeon commented on lua/entities/cfc_parachute/init.lua
> +    timer.Create( "CFC_Parachute_FollowOwner_" .. self:EntIndex(), 2, 0, function()
```suggestion
    timer.Create( timerNameFollowOwne, 2, 0, function()
```

2024-01-18 02:22 UTC, brandonsturgeon commented on lua/entities/cfc_parachute/init.lua
> +    end )
This might be better as a single timer with a loop

2024-01-18 02:22 UTC, brandonsturgeon commented on lua/entities/cfc_parachute/init.lua
> +    end
This issue seems solvable. I think relying on userinfo is the way to go.

Maybe:
- Remove `FCVAR_NEVER_AS_STRING` - I don't think it benefits you in this case
- Use their userinfo or default until you get an indication that they changed it

2024-01-18 02:22 UTC, brandonsturgeon commented on lua/entities/cfc_parachute/init.lua
> +end
Performance suggestion

```suggestion
do
    local IN_BACK = IN_BACK
    local IN_FORWARD = IN_FORWARD
    local IN_MOVELEFT  = IN_MOVELEFT
    local IN_MOVERIGHT = IN_MOVERIGHT

    function ENT:_KeyPress( ply, key, state )
        local selfTable = self:GetTable()
    
        if ply ~= selfTable._chuteOwner then return end
        if not MOVE_KEY_LOOKUP[key] then return end
    
        if key == IN_FORWARD then
            selfTable._chuteMoveForward = state and 1 or 0
        elseif key == IN_BACK then
            selfTable._chuteMoveBack = state and 1 or 0
        elseif key == IN_MOVERIGHT then
            selfTable._chuteMoveRight = state and 1 or 0
        elseif key == IN_MOVELEFT then
            selfTable._chuteMoveLeft = state and 1 or 0
        end
    
        if not selfTable._chuteIsOpen then return end
    
        self:_UpdateChuteDirection()
    end
end
```

2024-01-18 02:22 UTC, brandonsturgeon commented on lua/entities/cfc_parachute/shared.lua
> +ENT.Contact         = "CFC Discord"
```suggestion
ENT.Contact         = "https://discord.gg/cfc-servers"
```

2024-01-18 02:22 UTC, brandonsturgeon commented on lua/cfc_pvp_weapons/server/sv_parachute.lua
> +    newDesign = newDesign or 1
Could these ever be falsey? The code implies it's possible

If so, can we fix that?

2024-01-18 02:22 UTC, brandonsturgeon commented on lua/cfc_pvp_weapons/server/sv_parachute.lua
> +    end
I think there might be a typo here? The two checks are the same to my eyes

2024-01-18 02:22 UTC, brandonsturgeon commented on lua/cfc_pvp_weapons/server/sv_parachute.lua
> +    end, "CFC_Parachute_CacheValue" )
The callback names aren't necessary for these calls, and given that this section is pretty dense already, it could help the visual style of this block. Convars always suck for this reason, so any gains are welcome

2024-01-20 02:34 UTC, brandonsturgeon requested changes
A few more comments/questions, I also unresolved a few comments that weren't addressed from the last review.

2024-01-20 02:34 UTC, brandonsturgeon commented on lua/entities/cfc_parachute/init.lua
> +end
Micro-optimization:

```suggestion
local offsetVec = Vector()
local function getChutePos( owner )
    local plyHeight = owner:OBBMaxs().z -- mins z is always 0 for players.
    offsetVec[3] = CHUTE_OFFSET_HEIGHT * plyHeight / 72 -- Scale offset by player height.

    return owner:GetPos() + offsetVec
end
```

2024-01-20 02:34 UTC, brandonsturgeon commented on lua/cfc_pvp_weapons/server/sv_parachute_lfs.lua
> +-- Optional LFS integration.
Are we still keeping this? I thought we were going to ditch it

2024-01-20 05:07 UTC, legokidlogan commented on lua/cfc_pvp_weapons/client/cl_parachute.lua
> +    local hoverText = buttonData.HoverText or ( convar and convar:GetHelpText() )
Yes, some buttons don't use all of the values, such as the help button not using a convar. There were more examples before most of the buttons got axed, may as well leave this as-is in case new buttons are needed later.

2024-01-20 05:31 UTC, legokidlogan commented on lua/cfc_pvp_weapons/server/sv_parachute.lua
> +    end )
The negation is intentional, for the sake of performance, and to make the raw convar values more sensible and easier to edit for the end user.

2024-01-20 05:43 UTC, brandonsturgeon commented on lua/cfc_pvp_weapons/client/cl_parachute.lua
> +    local hoverText = buttonData.HoverText or ( convar and convar:GetHelpText() )
How about the on/off text? Your default case makes it seem like that should never happen

2024-01-20 05:48 UTC, legokidlogan commented on lua/cfc_pvp_weapons/server/sv_parachute_lfs.lua
> +-- Optional LFS integration.
The underused stuff (easy-enter, ejecting without a parachute) was removed. I'm keeping the parachute launch though because I've seen it help a lot of players of all ranks, most notably when their lfs got blown up.

2024-01-20 08:43 UTC, legokidlogan commented on lua/cfc_pvp_weapons/client/cl_parachute.lua
> +    local hoverText = buttonData.HoverText or ( convar and convar:GetHelpText() )
Either way, if someone generates a bad button, it will be easily apparent whether it spits out an error or has blatantly placeholder text. This is a non-issue.

Besides, someone who wants to add a button shouldn't be looking at this code snippet anyway. They should look at the comment block at the top of the file which details each parameter.

2024-01-20 10:11 UTC, brandonsturgeon commented on lua/cfc_pvp_weapons/client/cl_parachute.lua
> +    local hoverText = buttonData.HoverText or ( convar and convar:GetHelpText() )
That's definitely not true.

A visual oddity (`"[UNDEFINED]"`) can (and likely will) just be ignored by the player.

An actual error is sent to our tracker where we can fix the cause of it.

Besides, we shouldn't be treating it as something that could happen. **We** decide if a button has those fields.

2024-02-04 22:48 UTC, brandonsturgeon approved these changes
Looks good! Playtest went well. There were no urgent comments or suggestions.
Ready for merge!

Please undo the changes in:
- `lua/autorun/server/cfc_pvp_weapons_init.lua`
- `.github/workflows/deploy.yml`

Before merging, and then run the workshop deploy function after (squash) merging.

2024-02-04 22:52 UTC, merged