Grenades!
CFC-Servers/cfc_pvp_weapons pull request #68
Opened 2024-09-26 22:48 UTC by legokidlogan

Makes some improvements/fixes to the throwable and grenade bases, and adds some new grenades: discombob, impact discombob, cluster, super cluster, curse, and anti-gravity.

Requires https://github.com/CFC-Servers/cfc_ulx_commands/pull/159 to be merged.

2024-10-13 20:40 UTC, brandonsturgeon commented on lua/weapons/cfc_curse_grenade/shared.lua
> +            self:GetOwner():ChatPrint( "This server doesn't have the CFC ulx curse addon!" )
Is the curse grenade logic handled directly in cfc_ulx_commands?

2024-10-14 04:03 UTC, legokidlogan commented on lua/weapons/cfc_curse_grenade/shared.lua
> +            self:GetOwner():ChatPrint( "This server doesn't have the CFC ulx curse addon!" )
No, the grenade handles its own logic. However, cfc_ulx_commands is where all the curses are. Can't have a curse grenade without the curses.

2024-10-16 04:41 UTC, brandonsturgeon requested changes
Looks okay. A few comments and improvements.

I think the `Beep` functionality should be moved to a method on the base grenade class, also.

2024-10-16 04:41 UTC, brandonsturgeon commented on lua/cfc_pvp_weapons/server/utils.lua
> +--]]
```suggestion
--- Applies blast damage and optionally hooks into damage events.
--- 
--- @param dmgInfo CTakeDamageInfo The damage info object containing damage details.
--- @param pos Vector The position where the blast damage originates.
--- @param radius number The radius of the blast damage.
--- @param etdCallback function? A callback function for the `EntityTakeDamage` hook with `HOOK_LOW` priority. 
--- If the callback returns a value, it will be used in the hook, which can be used to block the normal damage event.
--- Do NOT call any damage-inflicting functions in this callback to avoid feedback loops or misattribution.
--- @param petdCallback? function A callback function for the `PostEntityTakeDamage` hook. 
--- Similar to `etdCallback`, but triggered after the entity takes damage.
---
--- **Note:** If you need to inflict additional damage from the callback, use a timer, entity with a fuse, or similar workaround.
```

2024-10-16 04:41 UTC, brandonsturgeon commented on lua/entities/cfc_simple_ent_antigrav_grenade.lua
> +    end
Does this actually need a timer?
```suggestion
    if not SERVER then return end
    if not fuseOnImpact then return end

    timer.Simple( 0, function()
        if not IsValid( self ) then return end

        local fuseShortened = false

        function self:PhysicsCollide()
            local fuseLeft = self._explodeDelay
            if not fuseLeft then return end
            if fuseShortened then return end

            fuseShortened = true

            if fuseLeft > fuseOnImpact then
                self:SetTimer( fuseOnImpact )
            end
        end
    end )
```

2024-10-16 04:41 UTC, brandonsturgeon commented on lua/entities/cfc_simple_ent_antigrav_grenade.lua
> +function ENT:CreateBubble()
nit: Could you localize angles/colors in here?

2024-10-16 04:41 UTC, brandonsturgeon commented on lua/entities/cfc_simple_ent_antigrav_grenade.lua
> +end
I don't think this is going to work like you think it will.

A much simpler and more reliable option:
- Simply deal the damage here
- Have a new `PostEntityTakeDamage` hook that checks for `cfc_simple_ent_antigrav_grenade` as the inflictor, and that `took == true`, and then run the second part of the effect

I believe the only difference will be that the bubbles will pop on non-pvpers, but I think that's fine

2024-10-16 04:41 UTC, brandonsturgeon commented on lua/entities/cfc_simple_ent_antigrav_grenade.lua
> +    util.ScreenShake( ent:EyePos(), 3, 5, 1.5, 500, true, ent )
Did you forget to use the recipientfilter here?

2024-10-16 04:41 UTC, brandonsturgeon commented on lua/entities/cfc_simple_ent_antigrav_grenade.lua
> +    end
```suggestion
    if not ent:IsOnGround() then return end

    ent:SetVelocity( Vector( 0, 0, self.PushStrength ) )
```

2024-10-16 04:41 UTC, brandonsturgeon commented on lua/entities/cfc_simple_ent_antigrav_grenade.lua
> +    end
Could you move this to a `ENT:Beep()` function that handles the rate limiting and so forth

2024-10-16 04:41 UTC, brandonsturgeon commented on lua/entities/cfc_simple_ent_bubble_grenade.lua
> +    end
Why not just use the function, wrapped or not?

2024-10-16 04:41 UTC, brandonsturgeon commented on lua/entities/cfc_simple_ent_bubble_grenade.lua
> +    -- No idea why that would happen, nor why it only happens with the cosmetic bubbles, but this fixes it.
Could you isolate and report this? Sounds like an easy bug report for rubat

2024-10-16 04:41 UTC, brandonsturgeon commented on lua/entities/cfc_simple_ent_cluster_grenade.lua
> +        timer.Simple( 0, function()
Is this timer needed? You're just defining a method on the entity

2024-10-16 04:41 UTC, brandonsturgeon commented on lua/entities/cfc_simple_ent_cluster_grenade.lua
> +        local physObj = ent:GetPhysicsObject()
nit: You can move this definition up above line 161

2024-12-01 02:04 UTC, legokidlogan commented on lua/entities/cfc_simple_ent_antigrav_grenade.lua
> +    end
Unfortunately, yes. Without the timer, it instantly triggers the physcollide upon spawning.

2024-12-01 02:11 UTC, legokidlogan commented on lua/entities/cfc_simple_ent_antigrav_grenade.lua
> +end
I can't use PETD because I don't want to actually deal damage, merely check to see if it would otherwise pass damage checks. Note how it adds a temporary, low-priority hook which blocks the damage.

Also it does work, it's been tested live on the server for over a week straight.

2024-12-01 02:17 UTC, legokidlogan commented on lua/entities/cfc_simple_ent_bubble_grenade.lua
> +    end
What? It *is* being used. This unwrap is needed here because of our own anticrash.

2024-12-01 02:18 UTC, legokidlogan commented on lua/entities/cfc_simple_ent_cluster_grenade.lua
> +        timer.Simple( 0, function()
Yes, otherwise the PhysCollide will run instantly.

2024-12-01 02:48 UTC, brandonsturgeon commented on lua/entities/cfc_simple_ent_bubble_grenade.lua
> +    end
What does our anticrash wrap do that doesn't work here?

2024-12-01 02:53 UTC, legokidlogan commented on lua/entities/cfc_simple_ent_bubble_grenade.lua
> +    end
It blocks scales above 3, and the bubbles go above that.

2024-12-02 03:57 UTC, brandonsturgeon commented on lua/entities/cfc_simple_ent_antigrav_grenade.lua
> +    end
Could you add a note in there explaining tha

2024-12-02 03:59 UTC, brandonsturgeon commented on lua/entities/cfc_simple_ent_antigrav_grenade.lua
> +end
I was saying you could deal 0 damage, and use PETD to verify that it actually passes all damage filters rather than toggling a hook in a Touch callback

2024-12-02 04:00 UTC, brandonsturgeon commented on lua/entities/cfc_simple_ent_bubble_grenade.lua
> +    end
Maybe we could exclude this on the anticrash side then? What if there are multiple wraps with different names and you don't actually get the unwrapped one you want

2024-12-02 04:16 UTC, legokidlogan commented on lua/entities/cfc_simple_ent_antigrav_grenade.lua
> +end
But if I do that, it'll create a hitmarker, and potentially other strange behavior from having the damage event make it all the way to PETD.

2024-12-02 04:22 UTC, legokidlogan commented on lua/entities/cfc_simple_ent_bubble_grenade.lua
> +    end
I could, but the only two ways I can think of aren't pretty. Either Making a hyper-specific name for the unwrapped function, or stuffing the wrapped function  with a new argument into to force-ignore the limit, which wouldn't be accessible by e2 or sf due to them not accounting for more arguments.

2024-12-06 08:32 UTC, brandonsturgeon approved these changes

2024-12-06 15:07 UTC, legokidlogan commented on lua/entities/cfc_simple_ent_bubble_grenade.lua
> +    end
That would be painfully specific, and add an __index call and long string comparison to every SetModelScale() call. If we do things on the anticrash's end, it should be generalizable.

2024-12-06 15:10 UTC, merged