Rescue lfs missilelauncher
CFC-Servers/cfc_pvp_weapons pull request #76
Opened 2024-12-30 23:12 UTC by StrawWagen

Removed all LFS systems, made it truly standalone.
Rename launcher, [LFS] Missile Launcher > Stinger Missile.

Use glide lockon warnings if we can.

Some balance tweaks too.
Increased lockon time.
Made it take ages to reload.
Buffed damage.
Decreased starting speed of the missile.
Decreased turn rate of the missile a bit.
Made it easier for the missile to "miss" and lose it's target.
Made the missile respect glide flares ( but with much more strict timing than the glide missiles )
Missile now wanders, isn't perfectly accurate when dumbfired.

Added custom kill/spawn icons aswell.

Fixed the style all over, spaces instead of tabs, lints properly too.

Should be ready to merge when we remove LFS, could merge early too, it doesn't conflict.

2025-01-10 15:31 UTC, legokidlogan requested changes

2025-01-10 15:31 UTC, legokidlogan commented on lua/entities/cfc_stinger_missile.lua
> +        if IsValid( pObj ) then
RERO

2025-01-10 15:31 UTC, legokidlogan commented on lua/entities/cfc_stinger_missile.lua
> +            end
These should be turned into constants.

2025-01-10 15:31 UTC, legokidlogan commented on lua/entities/cfc_stinger_missile.lua
> +    function ENT:FollowTarget( followEnt )
There's a lot of magic numbers here that should be turned into constants.

Also, imo the damage values should either be stored as `ENT.DamageValue = whatever` or directly from the convar, not local value * convar mult.

2025-01-10 15:31 UTC, legokidlogan commented on lua/entities/cfc_stinger_missile.lua
> +
```suggestion
```

2025-01-10 15:31 UTC, legokidlogan commented on lua/entities/cfc_stinger_missile.lua
> +                targetPos = followEnt:LocalToWorld( followsPhysObj:GetMassCenter() )
```suggestion
```
And remove `local followsPhysObj = followEnt:GetPhysicsObject()` above.
It's slightly faster to not deal with the physobj, and it avoids models with strange mass centers at the edges of or outside the model.

2025-01-10 15:31 UTC, legokidlogan commented on lua/entities/cfc_stinger_missile.lua
> +        end )
```suggestion
        local dmgMul = stingerDmgMulCvar:GetFloat()
        local inflictor = self:GetInflictor()
        local attacker = self:GetAttacker()
        local explodePos = self:WorldSpaceCenter()

        local effectdata = EffectData()
            effectdata:SetOrigin( self:GetPos() )
        util.Effect( "Explosion", effectdata )

        self:EmitSound( "vehicles/airboat/pontoon_impact_hard1.wav", 100, 50, 0.5 )
        self:EmitSound( "Explo.ww2bomb" )

        self:Remove()

        timer.Simple( 0, function()
            local fallbackDamager = Entity( 0 )
            inflictor = IsValid( inflictor ) and inflictor or fallbackDamager
            attacker = IsValid( attacker ) and attacker or fallbackDamager

            util.BlastDamage( inflictor, attacker, explodePos, 200 * dmgMul, 150 * dmgMul )
        end )
```

2025-01-10 15:31 UTC, legokidlogan commented on lua/entities/cfc_stinger_missile.lua
> +
Damage types are bitflags, you shouldn't compare directly.
```suggestion
        if not dmginfo:IsDamageType( DMG_AIRBOAT ) then return end
```

2025-01-10 15:31 UTC, legokidlogan commented on lua/weapons/cfc_stinger_launcher.lua
> +        SetGlobalInt( "cfc_stinger_maxrange", tonumber( value ) )
Just make the convar have FCVAR_REPLICATED and create it in both realms.

2025-01-10 15:31 UTC, legokidlogan commented on lua/weapons/cfc_stinger_launcher.lua
> +    return foundVehicles
```suggestion

    return foundVehicles
```

2025-01-10 15:31 UTC, legokidlogan commented on lua/weapons/cfc_stinger_launcher.lua
> +        for index, vehicle in ipairs( self.foundVehicles ) do
Removing indices will break when using `ipairs()`
```suggestion
        for i = #self.foundVehicles, 1, -1 do
            local vehicle = self.foundVehicles[i]

```
Then update `index` -> `i` and localize `self.foundVehicles`

2025-01-10 15:31 UTC, legokidlogan commented on lua/weapons/cfc_stinger_launcher.lua
> +
```suggestion
```

2025-01-10 15:31 UTC, legokidlogan commented on lua/weapons/cfc_stinger_launcher.lua
> +    return ( trResult.HitPos - pos ):Length() < 500
```suggestion

    return ( trResult.HitPos - pos ):Length() < 500
```

2025-01-10 15:31 UTC, legokidlogan commented on lua/weapons/cfc_stinger_launcher.lua
> +    self:SetNextSecondaryFire( CurTime() + 0.5 )
```suggestion

    self:SetNextSecondaryFire( CurTime() + 0.5 )

```

2025-01-10 15:31 UTC, legokidlogan commented on lua/weapons/cfc_stinger_launcher.lua
> +    return true
```suggestion

    return true
```

2025-01-10 15:31 UTC, legokidlogan commented on lua/weapons/cfc_stinger_launcher.lua
> +
```suggestion
```

2025-01-10 15:31 UTC, legokidlogan commented on lua/weapons/cfc_stinger_launcher.lua
> +    return true
```suggestion

    return true
```

2025-01-10 15:31 UTC, legokidlogan commented on lua/weapons/cfc_stinger_launcher.lua
> +
```suggestion
    local ply = LocalPlayer()
    if ply:InVehicle() then return end

    local ent = self:GetClosestEnt()
    if not IsValid( ent ) then return end

    local pos = ent:LocalToWorld( ent:OBBCenter() )
```

2025-01-10 15:31 UTC, legokidlogan commented on lua/weapons/cfc_stinger_launcher.lua
> +    local scrH = ScrH() / 2
nitpick: `scrW` for full width, `scrWH` for half width.
```suggestion
    local scrWH = ScrW() / 2
    local scrHH = ScrH() / 2
```
And update the vars below, of course.

2025-01-10 15:31 UTC, legokidlogan commented on lua/weapons/cfc_stinger_launcher.lua
> +    local Y = scr.y
```suggestion
    local x = scr.x
    local y = scr.y
```
And update below.

2025-01-10 15:31 UTC, legokidlogan commented on lua/weapons/cfc_stinger_launcher.lua
> +
```suggestion
```

2025-01-10 15:31 UTC, legokidlogan commented on lua/weapons/cfc_stinger_launcher.lua
> +
```suggestion
```

2025-01-10 15:31 UTC, legokidlogan commented on lua/weapons/cfc_stinger_launcher.lua
> +
```suggestion
```

2025-01-10 20:32 UTC, StrawWagen commented on lua/entities/cfc_stinger_missile.lua
> +    function ENT:FollowTarget( followEnt )
Resolved :)

2025-01-10 22:02 UTC, StrawWagen commented on lua/weapons/cfc_stinger_launcher.lua
> +        SetGlobalInt( "cfc_stinger_maxrange", tonumber( value ) )
cvars.AddChangeCallback doesn't work with FCVAR_REPLICATED

2025-01-10 22:18 UTC, StrawWagen commented on lua/weapons/cfc_stinger_launcher.lua
> +    local Y = scr.y
Applied

2025-01-10 22:18 UTC, StrawWagen commented on lua/weapons/cfc_stinger_launcher.lua
> +    local scrH = ScrH() / 2
Applied

2025-01-10 22:18 UTC, StrawWagen commented on lua/effects/cfc_stinger_trail.lua
> +                particle:SetDieTime( math.Rand( 3, 5 ) )
Applied

2025-01-10 22:18 UTC, StrawWagen commented on lua/effects/cfc_stinger_trail.lua
> +        local emitter = self.Emitter
Applied

2025-01-12 15:16 UTC, legokidlogan approved these changes

2025-01-12 21:49 UTC, merged